### ISSUE TITLE
Updates for the docker image but not here?

### ISSUE THREAD

**Issue by djmaze** [heiseonline/embetty-server#186]
The embetty-server image on dockerhub is seemingly [getting updates](https://hub.docker.com/r/heiseonline/embetty-server/tags) but there are no corresponding changes here. Was the development moved to an internal repo?

**Comment by level420** [comment]
I encountered the same question today. What do the updates on docker hub include?

**Comment by level420** [comment]
I'm not really sure, but it seems that the development of the embetty server moved over to https://github.com/heiseonline/embetty/tree/master/embetty-server

**Comment by StevenKowalzik** [comment]
The embetty server, base and component code was moved to the monorepo mentioned above. I'll mention this in the readme and mark this repository as archived, thanks for reminding!
