### ISSUE TITLE
YouTube IDs with dashes

### ISSUE THREAD

**Issue by medizinundmedien** [heiseonline/embetty-server#5]
The \w metacharacter at https://github.com/heiseonline/embetty-server/blob/7c7e751a6f423250919731d2019dc57d56972fb5/routes/video/youtube.js#L8 won't match all YouTube video IDs. YouTube video IDs can contain dashes (-) and underscores (_) – examples below:

https://www.youtube.com/watch?v=ZW9O45G-J1c
https://www.youtube.com/watch?v=RtU_mdL2vBM
https://www.youtube.com/watch?v=TK0-Qi0_SHg

A "better" pattern would check those characters with a length of 11 characters: /^[-_a-zA-Z0-9]{11}$/ instead of /^\w+$/

**Comment by compeak** [comment]
Thank you for reporting this bug. It has been fixed in 4aa837895eb7ae5be43a8f2b126c287a9c25573d.

[`\w` contains `_`.](https://www.w3schools.com/jsref/jsref_regexp_wordchar.asp)
