### ISSUE TITLE
Wrong default port listed on docs

### ISSUE THREAD

**Issue by jzaefferer** [heiseonline/embetty-server#6]
The README says that the PORT env var defaults to '3000', yet the docker-run example uses 8080. And the latter one works, so I guess the README is wrong. Not sure what its really supposed to be.

**Comment by compeak** [comment]
@jzaefferer The application server runs on port 3000, which is mapped to port 8080 by docker. So both ports are correct.

> The docker image exposes the server on port 8080 and can be configured using environment variables.

**Comment by jzaefferer** [comment]
More precise: The Dockerfile sets the PORT env var to change the application port to 8080, and then exposes that: https://github.com/heiseonline/embetty-server/blob/develop/Dockerfile#L3

But since it doesn't seem to bother anyone else, I suppose its fine.
