### ISSUE TITLE
Testing setup: Example URL for video

### ISSUE THREAD

**Issue by jzaefferer** [heiseonline/embetty-server#7]
Under https://github.com/heiseonline/embetty-server#testing-the-server-setup the only example is a tweet, but that first requires setting up a Twitter app. Since videos don't need that (right?), it would be nice to have an example with a video.

I tried http://localhost:8080/video/youtube/3L4fHrIJ3A4 and http://localhost:8080/video/3L4fHrIJ3A4 but neither worked

**Comment by compeak** [comment]
> I tried http://localhost:8080/video/youtube/3L4fHrIJ3A4 and http://localhost:8080/video/3L4fHrIJ3A4 but neither worked
@jzaefferer These routes do not exist. Try `/video/youtube/m6UOo2YGbIE-poster-image`.

> Since videos don't need that (right?), it would be nice to have an example with a video.
@jzaefferer I'll mention that in the readme.
